width: 2592
height: 1944
mode: 3
hflip: False
vflip: False
crop: (0.0, 0.0, 1.0, 1.0)
sharpness: 0
contrast: 0
brightness: 50
saturation: 0
ISO: 375
video_stabilization: False
exposure_compensation: 0
exposure_mode: 'auto'
meter_mode: 'average'
awb_mode: 'auto'
image_effect: 'none'
color_effects: 'none'
rotation: 0
drc: 'low'
shutter_speed: 100