# Size of the images 
width: 2592
height: 1944

# Sharpness: values between -100 and 100 (default: 0)
sharpness: 0

# Contrast: values between -100 and 100 (default: 0)
contrast: 0

# Brightness: values between 0 and 100 (default: 50)
brightness: 50

# ISO: values between 100 and 800 (default: automatic)
iso: 375

# Exposure mode (default: 'auto')
exposure_mode: 'auto'

# DRC control of the camera (increasing the range of dark areas): possibles
# values are 'off', 'low', 'medium' and 'high'
drc: 'low'

# Shutter speed in microseconds
shutter_speed: 3800

# Time in seconds of pre-capturing and post-capturing, respectively, 
# meanwhile the led is glowing
led_delay_on: 0
led_delay_off: 0

# Number of the GPIO pin that feeds the led light
led_pin_output: 24

# Number of the GPIO pin that controls RPi in slave mode
signal_pin_input: 23

# Number of the GPIO pins that show the state of the camera
state_red: 16
state_green: 20

# Time features (in seconds) of the camera state
time_green_led_out_of_time: 15
time_green_led_waiting_slave: 20
time_red_led: 300
time_between_flashes: 0.25
time_of_each_flash: 0.75

# Number of flashings of the led states
num_flashes_green_led_out_of_time: 3
num_flashes_green_led_waiting_slave: 5
num_flashes_red_led: 3

# Memory alarm threshold in kilobytes
memory_threshold: 1000000

#Sensors thresholds (temperature in celsius)
max_temp: 40
min_temp: 15
