# Folder name
mission_name: "prova"

# Operation mode: master or slave
# In slave, the GLIDER must send a signal to the RPi2
mode: "slave"

# Only in SLAVE mode
photos_per_cycle: 100

# Time in seconds between consecutive photos
period: 5

# Start and end dates of the mission
# Photos will be taken ONLY between those dates
start_date: "01/07/2015 06:30"
end_date: "08/07/2015 11:58"

