# Folder name where photos will be saved (if it doesn't 
# exist a new one will be created)
mission_name: "prova"

# Operation mode: master or slave
# In slave, the GLIDER must send a signal to the RPi2
mode: "master"

# Only in SLAVE mode
photos_per_cycle: 3

# Time in seconds between consecutive photos
period: 8

# Start and end dates of the mission
# Photos will be taken ONLY between those dates
start_date: "31/07/2015 07:33"
end_date: "31/07/2016 07:37"

